version: '3.3'
services:
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - /opt/dockerdata/sites/wordpress-prod/volumes/wordpress:/var/www/html
     working_dir: /var/www/html
     links:
       - db
     expose:
       - 80
     restart: always
     environment:
       - WORDPRESS_DB_HOST=db:3306
       - WORDPRESS_DB_USER
       - WORDPRESS_DB_PASSWORD
       - VIRTUAL_HOST
       - LETSENCRYPT_HOST
       - LETSENCRYPT_EMAIL


   db:
     image: mysql:5.7
     volumes:
       - /opt/dockerdata/sites/wordpress-prod/volumes/db_data:/var/lib/mysql
     restart: always
     environment:
       - MYSQL_ROOT_PASSWORD
       - MYSQL_DATABASE
       - MYSQL_USER
       - MYSQL_PASSWORD

networks:
  default:
    external:
      name: nginx-proxy
