version: '3.3'

services:
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - /opt/serverfiles/sites/dev/volumes/wordpress:/var/www/html
     working_dir: /var/www/html
     links:
      - db
     expose:
       - 80
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: my_wordpress_db_password
       VIRTUAL_HOST: dev.kobbl.co
       LETSENCRYPT_HOST: dev.kobbl.co
       LETSENCRYPT_EMAIL: niko@skyline.sbs


   db:
     image: mysql:5.7
     volumes:
       - /opt/serverfiles/sites/dev/volumes/db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: my_db_root_password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: my_wordpress_db_password

networks:
  default:
    external:
      name: nginx-proxy
